Windows path fix
dargmuesli/nuxt-cookie-control pull request #22
Opened 2023-01-14 11:35 UTC by zal1000

fix #14 
Tested on win11, devcontainer

2023-01-14 16:31 UTC, dargmuesli requested changes
Thank you for this fix, @zal1000!

Please make sure to follow linting rules as well as our [commit guideline](https://www.conventionalcommits.org/en/v1.0.0/). Alternatively, I can fix those errors for you if that's ok for you.

2023-01-14 16:31 UTC, dargmuesli commented on src/module.ts
> +    const path = !rpath.toLowerCase().startsWith("file://") || !rpath.toLowerCase().startsWith("/") ? `file://${rpath}` : rpath
I'm curious, how did you come up with those changes, especially the `file://` prefix?

2023-02-02 09:07 UTC, JulienChampagnol commented
Hi, any update on this?

2023-02-02 22:11 UTC, dargmuesli commented
Please follow the upstream issue for updates: https://github.com/nuxt/nuxt/issues/15500

2023-02-23 02:00 UTC, dargmuesli commented
Expecting the upstream issue to result in a fix, which would make PRs on downstream repos like this one redundant. Therefore, I'm closing this PR. Thank you for your work!

2023-02-23 02:00 UTC, closed without merging